apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: upz9ay94q-python
  janus-idp.io/tekton: upz9ay94q-python
  backstage.io/kubernetes-id: upz9ay94q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: upz9ay94q-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
