apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: upz9ay94q-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: upz9ay94q-python 
  name: upz9ay94q-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: upz9ay94q-python 
